### PR TITLE
Added ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

### PR DESCRIPTION
**Pull request by jussirantala**

### CODE REVIEW

**Comment by Aleksandern** [comment]
Thanks Jussi.

**Comment by jussirantala** [comment]
Maybe you should make a new version of this? npm is still installing the old one

**Comment by Aleksandern** [comment]
Sorry Jussi.. I forgot about npm... I've just published it.

**Comment by cinder92** [comment]
thanks!

**Pull request merged**
